version: '3.9'

services:
  db:
    image: postgres:14.1-alpine
    container_name: statdent-db-dev
    env_file:
      - .env
    ports:
      - "5433:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    restart: always

  api:
    container_name: statdent-api-dev
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - NODE_ENV=development
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules # evita conflictos entre host y container
    command: npm run start:dev
    depends_on:
      - db

volumes:
  postgres:
    name: statdent-db